# Generated by Django 4.2.2 on 2023-06-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rest_menu",
            "0004_remove_cartitem_total_price_alter_cart_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
