# Generated by Django 4.2.2 on 2023-06-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_menu", "0005_alter_cartitem_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="total_price",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="unit_price",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
