# Generated by Django 4.2.2 on 2023-06-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_menu", "0006_cartitem_total_price_alter_cartitem_unit_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
