# Generated by Django 4.2.2 on 2023-06-30 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rest_menu", "0007_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="delivered_at",
            new_name="status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_crew",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_crew",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="unit_price",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
