# Generated by Django 4.2.2 on 2023-06-30 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "rest_menu",
            "0008_rename_delivered_at_order_status_remove_order_items_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="deliverd_at",
            new_name="delivered_at",
        ),
    ]
